name: V8 Upgrade

on: workflow_dispatch

jobs:
    upgrade:
        name: Upgrade V8
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0
            - name: Update depot_tools fetch config
              run: cd deps/depot_tools && git config --unset-all remote.origin.fetch; git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
              shell: bash
            - name: Print $PATH
              run: echo "$PATH"
            - name: Add depot_tools to PATH
              run: echo "$PWD/deps/depot_tools" >> $GITHUB_PATH
              shell: bash
            - name: Print $PATH
              run: echo "$PATH"
            - name: Fetch V8
              run: cd deps && fetch v8 || true
            - name: Get latest stable version of v8
              id: v8_latest
              run: echo ::set-output name=V8LATEST::$(curl -sS 'https://omahaproxy.appspot.com/all.json?os=linux&channel=stable' | jq '.[0]["versions"][0]["v8_commit"]')
            - name: Print latest stable version of v8
              run: echo "${{steps.v8_latest.outputs.V8LATEST}}"
            - name: Display v8 branch info
              run: cd deps/v8 && git show ${{steps.v8_latest.outputs.V8LATEST}}
            - name: Swicth v8 to stable branch
              run: cd deps/v8 && git fetch && git checkout ${{steps.v8_latest.outputs.V8LATEST}}
            - name: Copy deps/v8/include into deps/include
              run: cp -r deps/v8/include/* deps/include/
            - name: Create PR
              uses: peter-evans/create-pull-request@v3
              with:
                commit-message: Update V8 binaries
                branch: update-v8-binary
                branch-suffix: random
                delete-branch: true
                title: Upgrade V8 binary
                body: Auto-generated pull request to upgarde V8 binary



